export const DUAS = [
  {
    id: "wake",
    title: "Waking up",
    bnTitle: "ঘুম থেকে ওঠা",
    tags: "wake morning sleep ঘুম ওঠা morning alhamdulillah",
    ar: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    bn: "সমস্ত প্রশংসা আল্লাহর, যিনি আমাদের মৃত্যুর পর জীবিত করলেন। তাঁরই দিকে পুনরুত্থান।",
    en: "All praise is for Allah who gave us life after causing us to die, and to Him is the resurrection.",
  },
  {
    id: "sleep",
    title: "Going to sleep",
    bnTitle: "ঘুমাতে যাওয়া",
    tags: "sleep bed night ঘুম রাত pillow",
    ar: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    bn: "হে আল্লাহ, তোমার নামেই আমি মরি এবং বাঁচি।",
    en: "In Your name, O Allah, I die and I live.",
  },
  {
    id: "eat-start",
    title: "Before eating",
    bnTitle: "খাওয়ার আগে",
    tags: "eat food meal breakfast lunch dinner খানা খাবার নাস্তা bismillah",
    ar: "بِسْمِ اللَّهِ",
    bn: "আল্লাহর নামে। (ভুলে গেলে: بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ)",
    en: "In the name of Allah. If you forgot: In the name of Allah at the beginning and the end.",
  },
  {
    id: "eat-end",
    title: "After eating",
    bnTitle: "খাওয়ার পরে",
    tags: "eat finish meal খানা শেষ alhamdulillah",
    ar: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
    bn: "সমস্ত প্রশংসা আল্লাহর, যিনি আমাদের খাওয়ালেন, পান করালেন এবং মুসলিম বানালেন।",
    en: "Praise be to Allah who fed us, gave us drink, and made us Muslims.",
  },
  {
    id: "drink",
    title: "Drinking water",
    bnTitle: "পানি পান",
    tags: "drink water পানি দুধ milk",
    ar: "بِسْمِ اللَّهِ — then after: الْحَمْدُ لِلَّهِ",
    bn: "শুরুতে বিসমিল্লাহ, শেষে আলহামদুলিল্লাহ। তিন শ্বাসে পান করা সুন্নত।",
    en: "Start with Bismillah, end with Alhamdulillah. Drink in three sips.",
  },
  {
    id: "toilet-in",
    title: "Entering the toilet",
    bnTitle: "টয়লেটে ঢোকা",
    tags: "toilet bathroom bathroom পাখানা bathroom restroom",
    ar: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",
    bn: "হে আল্লাহ, আমি অপবিত্র জিন (পুরুষ ও নারী) থেকে তোমার আশ্রয় চাই।",
    en: "O Allah, I seek refuge in You from the male and female unclean spirits.",
  },
  {
    id: "toilet-out",
    title: "Leaving the toilet",
    bnTitle: "টয়লেট থেকে বেরোনো",
    tags: "toilet leave bathroom",
    ar: "غُفْرَانَكَ",
    bn: "হে আল্লাহ, তোমার ক্ষমা চাই।",
    en: "I seek Your forgiveness.",
  },
  {
    id: "wudu",
    title: "Starting wudu",
    bnTitle: "ওযু শুরু",
    tags: "wudu ablution ওযু ozu",
    ar: "بِسْمِ اللَّهِ",
    bn: "আল্লাহর নামে ওযু শুরু করো।",
    en: "Begin wudu in the name of Allah.",
  },
  {
    id: "wudu-end",
    title: "After wudu",
    bnTitle: "ওযুর পরে",
    tags: "wudu finish shahada",
    ar: "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
    bn: "আমি সাক্ষ্য দিই আল্লাহ ছাড়া কোনো ইলাহ নেই, তিনি এক, তাঁর কোনো শরিক নেই। মুহাম্মদ তাঁর বান্দা ও রাসুল।",
    en: "I bear witness that there is no god but Allah alone, no partner, and Muhammad is His servant and messenger.",
  },
  {
    id: "home-out",
    title: "Leaving home",
    bnTitle: "বাড়ি থেকে বেরোনো",
    tags: "leave home বাড়ি বের travel work office",
    ar: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    bn: "আল্লাহর নামে, আমি আল্লাহর উপর ভরসা করলাম। কোনো শক্তি নেই আল্লাহ ছাড়া।",
    en: "In the name of Allah, I rely upon Allah. There is no power except with Allah.",
  },
  {
    id: "home-in",
    title: "Entering home",
    bnTitle: "বাড়িতে ঢোকা",
    tags: "enter home বাড়ি salam",
    ar: "بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا",
    bn: "আল্লাহর নামে আমরা ঢুকলাম, আল্লাহর নামে বেরোলাম, আর আমাদের রব আল্লাহর উপর ভরসা করলাম।",
    en: "In the name of Allah we enter, in the name of Allah we leave, and upon our Lord we rely.",
  },
  {
    id: "travel",
    title: "Starting a journey",
    bnTitle: "সফর / গাড়ি / বাস",
    tags: "travel car bus plane train গাড়ি বাস বিমান safar vehicle",
    ar: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنقَلِبُونَ",
    bn: "পবিত্র তিনি, যিনি একে আমাদের অধীন করেছেন। আমরা এতে সক্ষম ছিলাম না। আমরা আমাদের রবের দিকেই ফিরে যাব।",
    en: "Glory to Him who subjected this to us, and we could not have done it. Indeed we will return to our Lord.",
  },
  {
    id: "anxiety",
    title: "Anxiety, worry, stress",
    bnTitle: "দুশ্চিন্তা / টেনশন",
    tags: "anxiety worry stress fear nervous দুশ্চিন্তা টেনশন ভয় sad depression panic",
    ar: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
    bn: "আল্লাহই আমাদের জন্য যথেষ্ট, তিনি কতই না উত্তম কর্মবিধায়ক।",
    en: "Allah is sufficient for us, and He is the best disposer of affairs.",
  },
  {
    id: "distress",
    title: "Distress and hardship",
    bnTitle: "কষ্ট / বিপদ",
    tags: "hardship pain problem বিপদ কষ্ট trouble difficulty",
    ar: "لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
    bn: "তুমি ছাড়া কোনো ইলাহ নেই, তুমি পবিত্র। নিশ্চয়ই আমি যালিমদের অন্তর্ভুক্ত ছিলাম। (ইউনুসের দোয়া)",
    en: "There is no god but You, Glory be to You. Indeed I have been of the wrongdoers. (Dua of Yunus)",
  },
  {
    id: "forgiveness",
    title: "Seeking forgiveness",
    bnTitle: "ক্ষমা চাওয়া",
    tags: "forgive tawba istighfar গুনাহ ক্ষমা sin guilt",
    ar: "أَسْتَغْفِرُ اللَّهَ رَبِّي مِن كُلِّ ذَنبٍ وَأَتُوبُ إِلَيْهِ",
    bn: "আমি আমার রব আল্লাহর কাছে সব গুনাহের ক্ষমা চাই এবং তাঁর দিকে তওবা করি।",
    en: "I seek forgiveness from Allah, my Lord, from every sin, and I turn to Him.",
  },
  {
    id: "sayyidul",
    title: "Sayyidul istighfar",
    bnTitle: "সাইয়্যিদুল ইস্তিগফার",
    tags: "istighfar best forgiveness master",
    ar: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ...",
    bn: "হে আল্লাহ, তুমি আমার রব, তুমি ছাড়া ইলাহ নেই। তুমি আমাকে সৃষ্টি করেছ, আমি তোমার বান্দা। আমি আমার সাধ্যমতো তোমার অঙ্গীকার ও ওয়াদা পালন করি। আমি নিজের করা মন্দের অনিষ্ট থেকে তোমার আশ্রয় চাই। আমি তোমার দেয়া নেয়ামতের স্বীকার করি, আমি আমার গুনাহের স্বীকার করি। তাই আমাকে ক্ষমা করো। গুনাহ কেবল তুমিই ক্ষমা করো।",
    en: "O Allah, You are my Lord, none has the right to be worshipped but You. You created me and I am Your servant... forgive me, for none forgives sins but You.",
  },
  {
    id: "parents",
    title: "For parents",
    bnTitle: "মা-বাবার জন্য",
    tags: "parents mother father মা বাবা ammu abbu mom dad",
    ar: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    bn: "হে রব, তাদের প্রতি রহম করো, যেভাবে তারা ছোটবেলায় আমাকে লালন-পালন করেছেন।",
    en: "My Lord, have mercy upon them as they brought me up when I was small.",
  },
  {
    id: "knowledge",
    title: "For knowledge",
    bnTitle: "ইলম / পড়াশোনা",
    tags: "study exam knowledge ইলম পড়া পরীক্ষা school",
    ar: "رَبِّ زِدْنِي عِلْمًا",
    bn: "হে রব, আমার ইলম বাড়িয়ে দাও।",
    en: "My Lord, increase me in knowledge.",
  },
  {
    id: "guidance",
    title: "For guidance",
    bnTitle: "হেদায়েত",
    tags: "guidance hidayah সিদ্ধান্ত choice istikhara lost",
    ar: "اللَّهُمَّ اهْدِنِي وَسَدِّدْنِي",
    bn: "হে আল্লাহ, আমাকে হেদায়েত দাও এবং সঠিক পথে রাখো।",
    en: "O Allah, guide me and keep me steadfast.",
  },
  {
    id: "istikhara",
    title: "Istikhara (decision)",
    bnTitle: "ইস্তেখারা",
    tags: "istikhara decision job marriage সিদ্ধান্ত চাকরি বিয়ে choice",
    ar: "اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ...",
    bn: "হে আল্লাহ, তোমার ইলম দিয়ে আমি কল্যাণ চাই, তোমার ক্ষমতা দিয়ে শক্তি চাই। তুমি জানো, আমি জানি না। যদি এ কাজ আমার দ্বীন, দুনিয়া ও আখিরাতের জন্য ভালো হয়, তবে তা সহজ করে দাও। যদি খারাপ হয়, তবে ফিরিয়ে দাও এবং ভালো কিছু নির্ধারণ করো।",
    en: "O Allah, I seek the good from Your knowledge and ability from Your power... If this matter is good for my religion and my life, make it easy. If it is bad, turn it away and decree what is better.",
  },
  {
    id: "health",
    title: "For healing",
    bnTitle: "অসুখ / শিফা",
    tags: "sick illness health শিফা অসুখ pain fever hospital",
    ar: "اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ اشْفِ أَنْتَ الشَّافِي لَا شِفَاءَ إِلَّا شِفَاؤُكَ",
    bn: "হে মানুষের রব, কষ্ট দূর করো, সুস্থ করো। তুমিই শিফাদাতা। তোমার শিফা ছাড়া কোনো শিফা নেই।",
    en: "O Lord of the people, remove the harm and heal. You are the Healer. There is no healing except Your healing.",
  },
  {
    id: "protection",
    title: "Morning & evening protection",
    bnTitle: "সকাল-সন্ধ্যার হিফাজত",
    tags: "protection morning evening evil nazar evil eye সকাল সন্ধ্যা",
    ar: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    bn: "আল্লাহর নামে, যাঁর নামের সাথে আসমান-জমিনের কিছুই ক্ষতি করতে পারে না। তিনি সর্বশ্রোতা, সর্বজ্ঞ। (৩বার)",
    en: "In the name of Allah, with whose name nothing on earth or in heaven can harm. He is the All-Hearing, All-Knowing. (3 times)",
  },
  {
    id: "ayat-kursi",
    title: "Ayat al-Kursi (protection)",
    bnTitle: "আয়াতুল কুরসি",
    tags: "kursi protection sleep home শয়তান",
    ar: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ...",
    bn: "আল্লাহ, তিনি ছাড়া কোনো ইলাহ নেই, চিরঞ্জীব, সর্বসত্তার ধারক। তাঁকে তন্দ্রাও স্পর্শ করে না, নিদ্রাও নয়...",
    en: "Allah — there is no god except Him, the Ever-Living, the Sustainer. Neither drowsiness nor sleep overtakes Him...",
  },
  {
    id: "after-salah",
    title: "After salah",
    bnTitle: "সালাতের পরে",
    tags: "after prayer namaz salah tasbih",
    ar: "أستغفر الله (৩) · اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
    bn: "আল্লাহর ক্ষমা চাই (৩বার)। হে আল্লাহ, তুমি সালাম, তোমার থেকেই শান্তি। বরকতময় তুমি, হে মহিমা ও সম্মানের অধিকারী। তারপর ৩৩ তাসবিহ, ৩৩ তাহমিদ, ৩৩ তাকবির, ১ তাহলিল।",
    en: "Astaghfirullah ×3. O Allah, You are Peace and from You is peace... Then 33 SubhanAllah, 33 Alhamdulillah, 33 Allahu Akbar, 1 Tahlil.",
  },
  {
    id: "adhan",
    title: "After the adhan",
    bnTitle: "আজানের পরে",
    tags: "adhan azan আজান",
    ar: "اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ...",
    bn: "হে আল্লাহ, এই পরিপূর্ণ দাওয়াত ও কায়েম সালাতের রব, মুহাম্মদকে ওসিলা ও মর্যাদা দাও, এবং তাঁকে মাকামে মাহমুদে পৌঁছাও।",
    en: "O Allah, Lord of this perfect call and established prayer, grant Muhammad the wasilah and virtue, and raise him to the praised station.",
  },
  {
    id: "masjid-in",
    title: "Entering the masjid",
    bnTitle: "মসজিদে ঢোকা",
    tags: "masjid mosque মসজিদ",
    ar: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    bn: "হে আল্লাহ, আমার জন্য তোমার রহমতের দরজা খুলে দাও।",
    en: "O Allah, open for me the doors of Your mercy.",
  },
  {
    id: "masjid-out",
    title: "Leaving the masjid",
    bnTitle: "মসজিদ থেকে বেরোনো",
    tags: "masjid leave",
    ar: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
    bn: "হে আল্লাহ, আমি তোমার অনুগ্রহ চাই।",
    en: "O Allah, I ask You from Your bounty.",
  },
  {
    id: "anger",
    title: "When angry",
    bnTitle: "রাগ হলে",
    tags: "anger রাগ mad fight",
    ar: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
    bn: "আমি বিতাড়িত শয়তান থেকে আল্লাহর আশ্রয় চাই। (বসো, ওযু করো)",
    en: "I seek refuge in Allah from the accursed Shaytan. Sit down. Make wudu.",
  },
  {
    id: "rain",
    title: "When it rains",
    bnTitle: "বৃষ্টি",
    tags: "rain বৃষ্টি weather",
    ar: "اللَّهُمَّ صَيِّبًا نَافِعًا",
    bn: "হে আল্লাহ, একে উপকারী বৃষ্টি বানাও।",
    en: "O Allah, make it a beneficial downpour.",
  },
  {
    id: "thunder",
    title: "Thunder",
    bnTitle: "বজ্র",
    tags: "thunder storm বজ্র",
    ar: "سُبْحَانَ الَّذِي يُسَبِّحُ الرَّعْدُ بِحَمْدِهِ",
    bn: "পবিত্র তিনি, বজ্র যাঁর প্রশংসায় তাসবিহ পাঠ করে।",
    en: "Glory to Him whom thunder glorifies with praise.",
  },
  {
    id: "clothes",
    title: "Wearing clothes",
    bnTitle: "কাপড় পরা",
    tags: "clothes dress কাপড় new",
    ar: "الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا",
    bn: "সমস্ত প্রশংসা আল্লাহর, যিনি আমাকে এই পোশাক পরিয়েছেন।",
    en: "Praise be to Allah who clothed me with this.",
  },
  {
    id: "mirror",
    title: "Looking in the mirror",
    bnTitle: "আয়না",
    tags: "mirror আয়না handsome beauty",
    ar: "اللَّهُمَّ أَنْتَ حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي",
    bn: "হে আল্লাহ, তুমি আমার আকৃতি সুন্দর করেছ, আমার চরিত্রও সুন্দর করো।",
    en: "O Allah, You have made my form beautiful, so make my character beautiful.",
  },
  {
    id: "world-akhirah",
    title: "Good in this world and the next",
    bnTitle: "দুনিয়া ও আখিরাতের কল্যাণ",
    tags: "everything general success দুনিয়া আখিরাত hasanah",
    ar: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    bn: "হে আমাদের রব, দুনিয়াতে কল্যাণ দাও, আখিরাতে কল্যাণ দাও, আর আগুনের আজাব থেকে রক্ষা করো।",
    en: "Our Lord, give us good in this world and good in the Hereafter, and protect us from the Fire.",
  },
  {
    id: "debt",
    title: "For debt and provision",
    bnTitle: "ঋণ / রিজিক",
    tags: "debt money rizq রিজিক টাকা loan salary job",
    ar: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
    bn: "হে আল্লাহ, তোমার হালাল দিয়ে হারাম থেকে বাঁচাও, তোমার অনুগ্রহে অন্যের মুখাপেক্ষী হতে মুক্ত করো।",
    en: "O Allah, suffice me with what You have made lawful so I avoid the unlawful, and make me independent of all besides You.",
  },
  {
    id: "family",
    title: "For family and children",
    bnTitle: "পরিবার / সন্তান",
    tags: "family children wife husband সন্তান পরিবার",
    ar: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    bn: "হে রব, আমাদের স্ত্রী ও সন্তানদেরকে চোখের শীতলতা বানাও, আর আমাদেরকে মুত্তাকিদের নেতা বানাও।",
    en: "Our Lord, grant us from our spouses and children comfort to our eyes, and make us leaders of the righteous.",
  },
  {
    id: "qunut",
    title: "When you don't know what to ask",
    bnTitle: "যা খুশি বলতে পারো",
    tags: "anything everything help dua general যেকোনো",
    ar: "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي",
    bn: "হে রব, আমার বুক প্রশস্ত করো, আমার কাজ সহজ করো। নিজের ভাষায়ও আল্লাহর কাছে চাইতে পারো — তিনি সব ভাষা বোঝেন।",
    en: "My Lord, expand my chest and make my affair easy. You may also ask Allah in Bangla or English — He understands every tongue.",
  },
];

export function searchDuas(q) {
  const s = (q || "").trim().toLowerCase();
  if (!s) return DUAS;
  const words = s.split(/\s+/);
  const scored = DUAS.map((d) => {
    const hay = `${d.title} ${d.bnTitle} ${d.tags} ${d.en} ${d.bn}`.toLowerCase();
    let n = 0;
    for (const w of words) if (hay.includes(w)) n += 1;
    if (d.title.toLowerCase() === s || d.bnTitle === s) n += 5;
    return { d, n };
  }).filter((x) => x.n);
  scored.sort((a, b) => b.n - a.n);
  return scored.map((x) => x.d);
}
