/** Hanafi / Bangladesh. Fard counts are what you must pray. */
export const PRAYERS = {
  Fajr: {
    bn: "ফজর",
    fard: 2,
    units: [
      { count: 2, label: "Sunnah", bn: "সুন্নত" },
      { count: 2, label: "Fard", bn: "ফরজ" },
    ],
    voice: "Fard is recited out loud.",
    voiceBn: "ফরজ জোরে পড়তে হয়।",
    note: "Pray the 2 sunnah at home if you can, then 2 fard. After Fajr there is no extra namaz until sunrise.",
  },
  Dhuhr: {
    bn: "যোহর",
    fard: 4,
    units: [
      { count: 4, label: "Sunnah", bn: "সুন্নত" },
      { count: 4, label: "Fard", bn: "ফরজ" },
      { count: 2, label: "Sunnah", bn: "সুন্নত" },
    ],
    voice: "Fard is silent — lips move, no voice.",
    voiceBn: "ফরজ চুপে পড়তে হয়।",
    note: "The 4 sunnah before fard are muakkadah. If you are late, pray the 4 fard first.",
  },
  Asr: {
    bn: "আসর",
    fard: 4,
    units: [
      { count: 4, label: "Sunnah", bn: "সুন্নত (ঘায়র মুয়াক্কাদা)" },
      { count: 4, label: "Fard", bn: "ফরজ" },
    ],
    voice: "Fard is silent.",
    voiceBn: "ফরজ চুপে পড়তে হয়।",
    note: "The 4 sunnah before Asr are optional. Do not delay Asr until the sun goes pale.",
  },
  Maghrib: {
    bn: "মাগরিব",
    fard: 3,
    units: [
      { count: 3, label: "Fard", bn: "ফরজ" },
      { count: 2, label: "Sunnah", bn: "সুন্নত" },
    ],
    voice: "First 2 fard rakats out loud, 3rd silent.",
    voiceBn: "প্রথম দুই রাকাত জোরে, তৃতীয় রাকাত চুপে।",
    note: "Pray Maghrib soon after sunset. Sit for tashahhud after 2, then stand for the 3rd.",
  },
  Isha: {
    bn: "এশা",
    fard: 4,
    units: [
      { count: 4, label: "Fard", bn: "ফরজ" },
      { count: 2, label: "Sunnah", bn: "সুন্নত" },
      { count: 3, label: "Witr", bn: "বিতর" },
    ],
    voice: "First 2 fard rakats out loud, last 2 silent. Witr is wajib in Hanafi fiqh.",
    voiceBn: "প্রথম দুই রাকাত জোরে, শেষ দুই চুপে। বিতর ওয়াজিব।",
    note: "Witr is 3 rakats with one salam. In the 3rd rakat, after a short surah, say Allahu Akbar and recite dua qunut, then ruku.",
  },
};

export const STEPS = [
  {
    title: "Wudu & niyyah",
    bn: "ওযু করে কিবলামুখী দাঁড়াও। মনে মনে নিয়ত করো এই সালাতের।",
    en: "Wudu, face the Qibla, and intend this salah in your heart. No need to say the niyyah out loud.",
  },
  {
    title: "Takbir",
    bn: "হাত কানের কাছে তুলে আল্লাহু আকবার বলো। তারপর হাত নাভির নিচে ভাঁজ করো (হানাফি)।",
    en: "Raise hands to the ears: Allahu Akbar. Fold the right hand over the left, below the navel (Hanafi).",
    ar: "اللَّهُ أَكْبَرُ",
    pron: "Allahu Akbar",
  },
  {
    title: "Sana",
    bn: "চুপে সানা পড়ো। শুধু প্রথম রাকাতে।",
    en: "Quietly, first rakat only.",
    recites: ["sana"],
  },
  {
    title: "A'udhu + Bismillah",
    bn: "আউযুবিল্লাহ, তারপর বিসমিল্লাহ।",
    en: "Every rakat before Fatiha.",
    recites: ["audhu", "basmala"],
  },
  {
    title: "Al-Fatiha + a short surah",
    bn: "সূরা ফাতিহা ফরজ। তারপর আরও একটি ছোট সূরা (ফরজ/সুন্নত রাকাতে)। শেষে আমীন বলো।",
    en: "Fatiha is required every rakat. Then a short surah. Say Ameen after Fatiha.",
    recites: ["fatiha"],
  },
  {
    title: "Ruku",
    bn: "আল্লাহু আকবার বলে রুকু। পিঠ সোজা, তিনবার তাসবিহ।",
    en: "Allahu Akbar into ruku. Back level. Tasbih three times.",
    recites: ["ruku"],
  },
  {
    title: "Qawmah",
    bn: "সোজা হয়ে দাঁড়াও।",
    en: "Stand fully before going to sujud.",
    recites: ["qawmah"],
  },
  {
    title: "Sujud",
    bn: "আল্লাহু আকবার বলে সিজদা। কপাল, নাক, দুই হাত, দুই হাঁটু, দুই পা। তিনবার তাসবিহ। উঠে বসে আবার সিজদা।",
    en: "Two sujuds with a brief sit between. Forehead and nose on the ground.",
    recites: ["sujud", "jalsa"],
  },
  {
    title: "Next rakat",
    bn: "দ্বিতীয় রাকাতে সানা নেই। ফাতিহা + সূরা, রুকু, সিজদা। দুই রাকাতের পর বসে তাশাহহুদ।",
    en: "No sana after the first rakat. After 2 rakats, sit for tashahhud. If more remain, stand up after it.",
  },
  {
    title: "Last sitting",
    bn: "শেষ বৈঠকে তাশাহহুদ, দরুদ, দোয়া। তারপর ডানে সালাম, বামে সালাম।",
    en: "Tashahhud, durood, a short dua, then salam right and left.",
    recites: ["tashahhud", "durood", "salam"],
  },
];

export const RECITES = {
  sana: {
    title: "Sana",
    bnTitle: "সানা",
    ar: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَى جَدُّكَ وَلَا إِلٰهَ غَيْرُكَ",
    pron: "Subhanaka Allahumma wa bihamdika, wa tabarakasmuka, wa ta'ala jadduka, wa la ilaha ghayruk.",
    bn: "হে আল্লাহ, তুমি পবিত্র, তোমারই প্রশংসা। তোমার নাম বরকতময়, তোমার মহিমা উচ্চ। তুমি ছাড়া কোনো ইলাহ নেই।",
  },
  audhu: {
    title: "Ta'awwudh",
    bnTitle: "আউযুবিল্লাহ",
    ar: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
    pron: "A'udhu billahi minash-shaytanir-rajeem.",
    bn: "বিতাড়িত শয়তান থেকে আল্লাহর আশ্রয় চাই।",
  },
  basmala: {
    title: "Basmala",
    bnTitle: "বিসমিল্লাহ",
    ar: "بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ",
    pron: "Bismillahir-rahmanir-raheem.",
    bn: "পরম করুণাময়, অসীম দয়ালু আল্লাহর নামে।",
  },
  fatiha: {
    title: "Al-Fatiha",
    bnTitle: "সূরা ফাতিহা",
    ar: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمٰنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
    pron: "Alhamdu lillahi rabbil-'alameen. Ar-rahmanir-raheem. Maliki yawmid-deen. Iyyaka na'budu wa iyyaka nasta'een. Ihdinas-siratal-mustaqeem. Siratal-ladheena an'amta 'alayhim ghayril-maghdubi 'alayhim wa lad-dalleen.",
    bn: "সমস্ত প্রশংসা আল্লাহর, জগতসমূহের রব। পরম দয়াময়, অসীম দয়ালু। বিচারদিনের মালিক। আমরা শুধু তোমারই ইবাদত করি, শুধু তোমারই সাহায্য চাই। আমাদের সরল পথ দেখাও — যাদের তুমি নিয়ামত দিয়েছ তাদের পথ, যারা গজবে পতিত নয়, পথভ্রষ্টও নয়।",
  },
  ruku: {
    title: "In ruku",
    bnTitle: "রুকু",
    ar: "سُبْحَانَ رَبِّيَ الْعَظِيمِ",
    pron: "Subhana rabbiyal-'azeem. (3 times)",
    bn: "আমার মহান রব পবিত্র। তিনবার।",
  },
  qawmah: {
    title: "Standing after ruku",
    bnTitle: "কাওমা",
    ar: "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ ۝ رَبَّنَا لَكَ الْحَمْدُ",
    pron: "Sami'allahu liman hamidah. Rabbana lakal-hamd.",
    bn: "আল্লাহ শোনেন যে তাঁর প্রশংসা করে। হে আমাদের রব, প্রশংসা তোমারই।",
  },
  sujud: {
    title: "In sujud",
    bnTitle: "সিজদা",
    ar: "سُبْحَانَ رَبِّيَ الْأَعْلَى",
    pron: "Subhana rabbiyal-a'la. (3 times)",
    bn: "আমার সর্বোচ্চ রব পবিত্র। তিনবার।",
  },
  jalsa: {
    title: "Between sujuds",
    bnTitle: "দুই সিজদার মাঝে",
    ar: "رَبِّ اغْفِرْ لِي",
    pron: "Rabbighfir li.",
    bn: "হে রব, আমাকে ক্ষমা করো।",
  },
  tashahhud: {
    title: "Tashahhud",
    bnTitle: "তাশাহহুদ",
    ar: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَىٰ عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلٰهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
    pron: "At-tahiyyatu lillahi was-salawatu wat-tayyibat. As-salamu 'alayka ayyuhan-nabiyyu wa rahmatullahi wa barakatuh. As-salamu 'alayna wa 'ala 'ibadillahis-saliheen. Ashhadu an la ilaha illallahu wa ashhadu anna Muhammadan 'abduhu wa rasuluh.",
    bn: "সব সম্মান, ইবাদত ও পবিত্র কথা আল্লাহর। হে নবী, তোমার প্রতি শান্তি, আল্লাহর রহমত ও বরকত। আমাদের ও নেক বান্দাদের প্রতি শান্তি। আমি সাক্ষ্য দিই আল্লাহ ছাড়া কোনো ইলাহ নেই, মুহাম্মদ তাঁর বান্দা ও রাসুল।",
  },
  durood: {
    title: "Durood",
    bnTitle: "দরুদ",
    ar: "اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ",
    pron: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammad, kama sallayta 'ala Ibraheema wa 'ala ali Ibraheem. Innaka hameedun majeed.",
    bn: "হে আল্লাহ, মুহাম্মদ ও তাঁর পরিজনের প্রতি রহমত নাযিল করো, যেমন ইবরাহিম ও তাঁর পরিজনের প্রতি করেছ। তুমি প্রশংসিত, মহিমান্বিত।",
  },
  salam: {
    title: "Salam",
    bnTitle: "সালাম",
    ar: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ",
    pron: "As-salamu 'alaykum wa rahmatullah. (right, then left)",
    bn: "তোমাদের প্রতি শান্তি ও আল্লাহর রহমত। প্রথমে ডানে, তারপর বামে।",
  },
};

/** Short surahs commonly used after Fatiha. page = 15-line Madinah mushaf. */
export const NAMAZ_SURAHS = [
  {
    id: "fatiha",
    no: 1,
    page: 1,
    title: "Al-Fatiha",
    bnTitle: "আল-ফাতিহা",
    need: "Every rakat — without this the rakat is not valid.",
    needBn: "প্রতি রাকাতে ফরজ।",
    ar: RECITES.fatiha.ar,
    pron: RECITES.fatiha.pron,
    bn: RECITES.fatiha.bn,
  },
  {
    id: "ikhlas",
    no: 112,
    page: 604,
    title: "Al-Ikhlas",
    bnTitle: "আল-ইখলাস",
    need: "The shortest complete surah. Learn this first after Fatiha.",
    needBn: "ফাতিহার পর প্রথম যেটা মুখস্থ করো।",
    ar: "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
    pron: "Qul huwallahu ahad. Allahus-samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.",
    bn: "বলো, তিনি আল্লাহ, এক। আল্লাহ অমুখাপেক্ষী। তিনি জন্ম দেননি, জন্ম নেননি। তাঁর সমকক্ষ কেউ নেই।",
  },
  {
    id: "falaq",
    no: 113,
    page: 604,
    title: "Al-Falaq",
    bnTitle: "আল-ফালাক",
    need: "Often paired with An-Nas after Maghrib / before sleep, and in namaz.",
    needBn: "নামাজে ও সকাল-সন্ধ্যায় পড়া যায়।",
    ar: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
    pron: "Qul a'udhu bi rabbil-falaq. Min sharri ma khalaq. Wa min sharri ghasiqin idha waqab. Wa min sharrin-naffathati fil-'uqad. Wa min sharri hasidin idha hasad.",
    bn: "বলো, আমি আশ্রয় চাই প্রভাতের রবের কাছে — তাঁর সৃষ্টির অনিষ্ট থেকে, রাতের অন্ধকার থেকে, গিরায় ফুঁক দেওয়াদের অনিষ্ট থেকে, হিংসুকের হিংসা থেকে।",
  },
  {
    id: "nas",
    no: 114,
    page: 604,
    title: "An-Nas",
    bnTitle: "আন-নাস",
    need: "Last surah of the Quran. Use in any rakat after Fatiha.",
    needBn: "কুরআনের শেষ সূরা। যেকোনো রাকাতে পড়া যায়।",
    ar: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلٰهِ النَّاسِ ۝ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ",
    pron: "Qul a'udhu bi rabbin-nas. Malikin-nas. Ilahin-nas. Min sharril-waswasil-khannas. Alladhi yuwaswisu fi sudurin-nas. Minal-jinnati wan-nas.",
    bn: "বলো, আমি আশ্রয় চাই মানুষের রব, মানুষের বাদশাহ, মানুষের ইলাহের কাছে — কুমন্ত্রণাকারীর অনিষ্ট থেকে, যে মানুষের অন্তরে কুমন্ত্রণা দেয়, জিন ও মানুষ থেকে।",
  },
  {
    id: "kawthar",
    no: 108,
    page: 602,
    title: "Al-Kawthar",
    bnTitle: "আল-কাওসার",
    need: "Three lines. Easy for a second rakat.",
    needBn: "মাত্র তিন আয়াত — দ্বিতীয় রাকাতের জন্য সহজ।",
    ar: "إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ ۝ فَصَلِّ لِرَبِّكَ وَانْحَرْ ۝ إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ",
    pron: "Inna a'taynakal-kawthar. Fasalli li rabbika wanhar. Inna shani'aka huwal-abtar.",
    bn: "আমি তোমাকে কাওসার দিয়েছি। তাই তোমার রবের জন্য সালাত পড়ো ও কুরবানি করো। তোমার বিদ্বেষীই নির্বংশ।",
  },
  {
    id: "asr",
    no: 103,
    page: 601,
    title: "Al-Asr",
    bnTitle: "আল-আসর",
    need: "Short, and the meaning is a reminder after Asr namaz too.",
    needBn: "ছোট, অর্থও নামাজের পর মনে রাখার মতো।",
    ar: "وَالْعَصْرِ ۝ إِنَّ الْإِنسَانَ لَفِي خُسْرٍ ۝ إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ",
    pron: "Wal-'asr. Innal-insana lafi khusr. Illal-ladheena amanu wa 'amilus-salihati wa tawasaw bil-haqqi wa tawasaw bis-sabr.",
    bn: "সময়ের শপথ। মানুষ অবশ্যই ক্ষতির মধ্যে — তারা ছাড়া যারা ঈমান আনে, নেক আমল করে, সত্য ও ধৈর্যে একে অপরকে উপদেশ দেয়।",
  },
  {
    id: "kafirun",
    no: 109,
    page: 603,
    title: "Al-Kafirun",
    bnTitle: "আল-কাফিরুন",
    need: "Often the first rakat; pair with Al-Ikhlas in the second.",
    needBn: "প্রথম রাকাতে এটা, দ্বিতীয়ে ইখলাস — প্রচলিত জোড়া।",
    ar: "قُلْ يَا أَيُّهَا الْكَافِرُونَ ۝ لَا أَعْبُدُ مَا تَعْبُدُونَ ۝ وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ ۝ وَلَا أَنَا عَابِدٌ مَّا عَبَدتُّمْ ۝ وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ ۝ لَكُمْ دِينُكُمْ وَلِيَ دِينِ",
    pron: "Qul ya ayyuhal-kafirun. La a'budu ma ta'budun. Wa la antum 'abiduna ma a'bud. Wa la ana 'abidum ma 'abadtum. Wa la antum 'abiduna ma a'bud. Lakum deenukum wa liya deen.",
    bn: "বলো, হে কাফিররা, তোমরা যার ইবাদত করো তার ইবাদত আমি করি না। আমি যার ইবাদত করি তার ইবাদত তোমরা করো না। তোমাদের দ্বীন তোমাদের, আমার দ্বীন আমার।",
  },
  {
    id: "nasr",
    no: 110,
    page: 603,
    title: "An-Nasr",
    bnTitle: "আন-নাসর",
    need: "Three ayahs. Good when you already know Ikhlas and Kawthar.",
    needBn: "তিন আয়াত। ইখলাস শেখার পর এটা নাও।",
    ar: "إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ ۝ وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا ۝ فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ ۚ إِنَّهُ كَانَ تَوَّابًا",
    pron: "Idha ja'a nasrullahi wal-fath. Wa ra'aytan-nasa yadkhuluna fi deenillahi afwaja. Fasabbih bihamdi rabbika wastaghfirh. Innahu kana tawwaba.",
    bn: "যখন আল্লাহর সাহায্য ও বিজয় আসে, আর মানুষ দলে দলে আল্লাহর দ্বীনে প্রবেশ করে, তখন তোমার রবের প্রশংসায় তাসবিহ পড়ো এবং ক্ষমা চাও। তিনি তওবা কবুলকারী।",
  },
  {
    id: "qadr",
    no: 97,
    page: 598,
    title: "Al-Qadr",
    bnTitle: "আল-কদর",
    need: "Laylatul Qadr. Useful in Ramadan witr and night namaz.",
    needBn: "শবে কদর। রমজানের বিতরে কাজে লাগে।",
    ar: "إِنَّا أَنزَلْنَاهُ فِي لَيْلَةِ الْقَدْرِ ۝ وَمَا أَدْرَاكَ مَا لَيْلَةُ الْقَدْرِ ۝ لَيْلَةُ الْقَدْرِ خَيْرٌ مِّنْ أَلْفِ شَهْرٍ ۝ تَنَزَّلُ الْمَلَائِكَةُ وَالرُّوحُ فِيهَا بِإِذْنِ رَبِّهِم مِّن كُلِّ أَمْرٍ ۝ سَلَامٌ هِيَ حَتَّىٰ مَطْلَعِ الْفَجْرِ",
    pron: "Inna anzalnahu fi laylatil-qadr. Wa ma adraka ma laylatul-qadr. Laylatul-qadri khayrun min alfi shahr. Tanazzalul-mala'ikatu war-ruhu fiha bi idhni rabbihim min kulli amr. Salamun hiya hatta matla'il-fajr.",
    bn: "আমি এটি নাযিল করেছি কদরের রাতে। কদরের রাত হাজার মাস অপেক্ষা শ্রেষ্ঠ। সে রাতে ফজর পর্যন্ত সালাম।",
  },
  {
    id: "maun",
    no: 107,
    page: 602,
    title: "Al-Ma'un",
    bnTitle: "আল-মাউন",
    need: "About salah done for show. A reminder while you learn the motions.",
    needBn: "লোকদেখানো নামাজের সতর্কবার্তা।",
    ar: "أَرَأَيْتَ الَّذِي يُكَذِّبُ بِالدِّينِ ۝ فَذَٰلِكَ الَّذِي يَدُعُّ الْيَتِيمَ ۝ وَلَا يَحُضُّ عَلَىٰ طَعَامِ الْمِسْكِينِ ۝ فَوَيْلٌ لِّلْمُصَلِّينَ ۝ الَّذِينَ هُمْ عَن صَلَاتِهِمْ سَاهُونَ ۝ الَّذِينَ هُمْ يُرَاءُونَ ۝ وَيَمْنَعُونَ الْمَاعُونَ",
    pron: "Ara'aytal-ladhi yukadhdhibu bid-deen. Fadhalikal-ladhi yadu''ul-yateem. Wa la yahuddu 'ala ta'amil-miskeen. Fawaylun lil-musalleen. Alladheena hum 'an salatihim sahoon. Alladheena hum yura'oon. Wa yamna'unal-ma'un.",
    bn: "যে বিচারদিনকে অস্বীকার করে, যে এতিমকে ধাক্কা দেয়, মিসকিনকে খাবার দিতে উৎসাহ দেয় না — দুর্ভোগ সেই মুসল্লিদের যারা নামাজে উদাসীন, লোকদেখানো করে, এবং ছোট সাহায্যও আটকে রাখে।",
  },
];
